keys:
  - &main_key age1hl8zqn7j9k6j8k8k8k8k8k8k8k8k8k8k8k8k8k8k8k8k8k8k8k8k8k8k

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
    - age:
      - *main_key
  - path_regex: secrets/.*\.json$
    key_groups:
    - age:
      - *main_key
  - path_regex: secrets/.*\.env$
    key_groups:
    - age:
      - *main_key