keys:
  - &main_key age14az8mfangvw8fj6yanxv3zvfeya7fjjzcl9fnfctvsp6zg0acuuss8tftw

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
    - age:
      - *main_key
  - path_regex: secrets/.*\.json$
    key_groups:
    - age:
      - *main_key
  - path_regex: secrets/.*\.env$
    key_groups:
    - age:
      - *main_key